version: "3.7"

services:
  bot:
    user: root
    environment:
      - DISCORD_BOT_TOKEN
      - GDN_API_TOKEN
      - PAPERTRAIL_HOST
      - PAPERTRAIL_PORT
    volumes:
      # Preserve the settings database on the host filesystem
      - ./settings.db:/usr/src/app/settings.db:rw
    networks:
      - gdn_network
    command: "npm run host"
    restart: unless-stopped:0

networks:
  # This allows GDNBot to communicate with the API server via Nginx.
  # see the backend's docker-compose.yml
  gdn_network:
    external: true
    name: backend-network
